# Build settings
markdown: kramdown
permalink: /:title/
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]

# GitHub Pages settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Kramdown settings
kramdown:
  input: GFM
  auto_ids: true
  footnote_backlink: "&#8617;"
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  toc_levels: 1..3
  toc_footers:
    - "<a href='#'>Back to top</a>"
