# Site settings
title: Ted Harrison - Technical Writer
description: Showcase your technical writing skills and expertise
url: https://tward212.github.io
baseurl: "" # if your site is hosted on a subpath, enter the subpath here (e.g., /portfolio)

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# GitHub Pages settings
remote_theme: "pages-themes/minimal"
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock]
